name: 0.3 blocker

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  version-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        if: github.base_ref == 'master' && github.head_ref != 'master-0.3'
        env:
          REPO: ${{ github.server_url }}/${{ github.repository }}.git
        run: git clone --filter=tree:0 --bare "$REPO" .
      - name: Check requirements
        if: github.base_ref == 'master' && github.head_ref != 'master-0.3'
        run: |
          DISALLOWED_COMMIT="ba8550f62c356a89cdddf9f218f9ad227b21403c"
          if git log "$GITHUB_SHA" --pretty=%H | grep "$DISALLOWED_COMMIT" > /dev/null; then
            echo "there is disallowed commit"
            exit 1
          else
            echo "there is no disallowed commit"
            exit 0
          fi
